# Generated by Django 5.0.7 on 2026-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_tracking', '0003_add_reset_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingnumbersequence',
            options={'ordering': ['-year', '-month', 'document_type'], 'verbose_name': 'Tracking Number Sequence', 'verbose_name_plural': 'Tracking Number Sequences'},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='reset_annually',
            field=models.BooleanField(default=True, help_text='DEPRECATED: Use reset_policy instead. Reset serial number to 1 each year'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='reset_policy',
            field=models.CharField(choices=[('none', 'Never reset (continuous sequence)'), ('monthly', 'Reset monthly'), ('yearly', 'Reset yearly')], default='yearly', help_text='When to reset the sequence counter (applies to auto mode only)', max_length=10),
        ),
        migrations.AlterField(
            model_name='trackingnumbersequence',
            name='month',
            field=models.IntegerField(blank=True, help_text='Month for monthly sequences (1-12, null for yearly/continuous)', null=True),
        ),
    ]
