# Generated by Django 5.2.9 on 2026-01-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workitemreadstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_images/'),
        ),
    ]
