# Generated by Django 5.2.9 on 2026-01-07 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workitem_inactive_by_alter_workitem_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgassignment',
            name='division',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'division'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_assignments', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='orgassignment',
            name='section',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'section'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_assignments', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='orgassignment',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='orgassignment',
            name='unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'unit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_assignments', to='accounts.team'),
        ),
    ]
