# Generated by Django 5.0.7 on 2026-01-14 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_orgassignment_division_and_more'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_items', models.PositiveIntegerField(default=0, help_text='Total work items assigned to user')),
                ('completed_work_items', models.PositiveIntegerField(default=0, help_text='Work items marked as done')),
                ('on_time_submissions', models.PositiveIntegerField(default=0, help_text='Submissions made before deadline')),
                ('late_submissions', models.PositiveIntegerField(default=0, help_text='Submissions made after deadline')),
                ('approved_work_items', models.PositiveIntegerField(default=0, help_text='Work items approved by admin')),
                ('revision_requests', models.PositiveIntegerField(default=0, help_text='Work items sent back for revision')),
                ('total_files_uploaded', models.PositiveIntegerField(default=0, help_text='Total files uploaded by user')),
                ('accepted_files', models.PositiveIntegerField(default=0, help_text='Files accepted by admin')),
                ('rejected_files', models.PositiveIntegerField(default=0, help_text='Files rejected by admin')),
                ('on_time_ratio', models.FloatField(default=0.0, help_text='Percentage of on-time submissions (0-100)')),
                ('approval_ratio', models.FloatField(default=0.0, help_text='Percentage of approved work items (0-100)')),
                ('file_acceptance_ratio', models.FloatField(default=0.0, help_text='Percentage of accepted files (0-100)')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, help_text='When metrics were last recalculated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
            },
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Admin acceptance status for this file', max_length=20),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the file was accepted', null=True),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the file was rejected', null=True),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='rejection_expires_at',
            field=models.DateTimeField(blank=True, help_text='When rejected file will be auto-deleted (24h after rejection)', null=True),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Optional reason for rejection', max_length=255),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who accepted/rejected this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['acceptance_status'], name='accounts_wo_accepta_a022ce_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['rejection_expires_at'], name='accounts_wo_rejecti_abaa88_idx'),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
    ]
