# Generated by Django 5.0.7 on 2026-01-14 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_file_acceptance_and_user_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_type', models.CharField(choices=[('work_item', 'Work Item'), ('workcycle', 'Work Cycle'), ('user_thread', 'User Thread')], default='work_item', max_length=20)),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('hidden_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_discussions', to=settings.AUTH_USER_MODEL)),
                ('hidden_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads_hidden_by_admins', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='accounts.workitem')),
                ('workcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_admins', to='accounts.workcycle')),
            ],
            options={
                'indexes': [models.Index(fields=['hidden_by', 'hide_type'], name='accounts_hi_hidden__7179bf_idx'), models.Index(fields=['hidden_by', 'work_item'], name='accounts_hi_hidden__c7a687_idx'), models.Index(fields=['hidden_by', 'workcycle'], name='accounts_hi_hidden__3e346c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hiddendiscussion',
            constraint=models.UniqueConstraint(condition=models.Q(('hide_type', 'work_item')), fields=('hidden_by', 'work_item'), name='unique_hidden_work_item'),
        ),
        migrations.AddConstraint(
            model_name='hiddendiscussion',
            constraint=models.UniqueConstraint(condition=models.Q(('hide_type', 'workcycle')), fields=('hidden_by', 'workcycle'), name='unique_hidden_workcycle'),
        ),
        migrations.AddConstraint(
            model_name='hiddendiscussion',
            constraint=models.UniqueConstraint(condition=models.Q(('hide_type', 'user_thread')), fields=('hidden_by', 'hidden_user', 'workcycle'), name='unique_hidden_user_thread'),
        ),
    ]
