# Generated by Django 5.0.7 on 2026-01-19 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_switch_to_local_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitemattachment',
            name='attachment_type',
            field=models.CharField(choices=[('matrix_a', 'Matrix A'), ('matrix_b', 'Matrix B'), ('mov', 'MOV'), ('document', 'Document')], db_index=True, default='document', help_text='Type of attachment (matrix_a, matrix_b, mov for work items; document for standalone)', max_length=20),
        ),
        migrations.AlterField(
            model_name='workitemattachment',
            name='work_item',
            field=models.ForeignKey(blank=True, help_text='Work item this file belongs to (null for standalone file manager uploads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.workitem'),
        ),
    ]
