# Generated by Django 5.0.7 on 2026-01-21 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_workcycle_job_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemReviewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_decision', models.CharField(max_length=30)),
                ('new_decision', models.CharField(max_length=30)),
                ('file_stats', models.JSONField(blank=True, default=dict, help_text='File statistics (accepted/rejected counts, file names)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workitem_review_jobs', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_jobs', to='accounts.workitem')),
            ],
            options={
                'db_table': 'workitem_review_jobs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='workitem_re_status_c60052_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkItemStatusJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workitem_status_jobs', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_jobs', to='accounts.workitem')),
            ],
            options={
                'db_table': 'workitem_status_jobs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='workitem_st_status_1348bd_idx')],
            },
        ),
    ]
