# Generated by Django 5.0.7 on 2026-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_workitem_job_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemattachment',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL for link attachments (alternative to file upload)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workitemattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file (null for link attachments)', null=True, upload_to='work_items/'),
        ),
    ]
