# Generated by Django 5.0.7 on 2026-01-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_link_url_to_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemattachment',
            name='link_title',
            field=models.CharField(blank=True, help_text='Title/name for link attachments (displayed in file manager)', max_length=255, null=True),
        ),
    ]
