# Generated by Django 5.0.7 on 2026-02-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document type name (e.g., Memorandum, Letter, Report)', max_length=100, unique=True)),
                ('prefix', models.CharField(help_text='Tracking number prefix (2-5 uppercase letters, e.g., MEM, LTR, RPT)', max_length=5, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this document type')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active document types appear in submission forms')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('serial_mode', models.CharField(choices=[('auto', 'Auto-generate'), ('manual', 'Manual entry'), ('both', 'Both (admin chooses)')], default='auto', help_text='How serial numbers are assigned', max_length=10)),
                ('reset_annually', models.BooleanField(default=True, help_text='Reset serial number to 1 each year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section/Department name (e.g., licensing, enforcement, admin)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the section', max_length=150)),
                ('description', models.TextField(blank=True, help_text="Optional description of this section's responsibilities")),
                ('is_active', models.BooleanField(default=True, help_text='Active sections appear in submission forms')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officers', models.ManyToManyField(blank=True, help_text='Users assigned as officers for this section', related_name='document_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Unique tracking number (assigned by admin)', max_length=50, null=True, unique=True)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('purpose', models.TextField(help_text='Purpose of the document submission')),
                ('document_type', models.CharField(choices=[('permit', 'Permit'), ('inspection', 'Inspection'), ('memo', 'Memo'), ('others', 'Others')], help_text='Type of document for routing', max_length=20)),
                ('status', models.CharField(choices=[('pending_tracking', 'Pending Tracking Assignment'), ('received', 'Received'), ('under_review', 'Under Review'), ('for_compliance', 'For Compliance'), ('returned_to_sender', 'Returned to Sender'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_tracking', help_text='Current workflow status', max_length=50)),
                ('is_stored_in_file_manager', models.BooleanField(default=False, help_text='True if submission files have been moved to File Manager (happens on approval)')),
                ('is_locked', models.BooleanField(default=False, help_text='Record is locked (read-only) after archival')),
                ('tracking_locked', models.BooleanField(default=False, help_text='Tracking number is locked and cannot be modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_folder', models.ForeignKey(blank=True, help_text='Archive storage folder for archived files (DEPRECATED - use file_manager_folder)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_submissions', to='structure.documentfolder')),
                ('assigned_section', models.ForeignKey(blank=True, help_text='Section assigned to process this submission', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='document_tracking.section')),
                ('doc_type', models.ForeignKey(blank=True, help_text='Document type (for tracking number generation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='document_tracking.documenttype')),
                ('file_manager_folder', models.ForeignKey(blank=True, help_text='File Manager folder where approved submission files are stored (ROOT > Year > Submissions > Title)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_submissions', to='structure.documentfolder')),
                ('primary_folder', models.ForeignKey(blank=True, help_text='Primary storage folder for submission files', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_submissions', to='structure.documentfolder')),
                ('submitted_by', models.ForeignKey(help_text='User who submitted the document', on_delete=django.db.models.deletion.PROTECT, related_name='document_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Submission Created'), ('tracking_assigned', 'Tracking Assigned'), ('status_changed', 'Status Changed'), ('files_uploaded', 'Files Uploaded'), ('archived', 'Archived'), ('reset_to_start', 'Reset to Start'), ('undo_action', 'Undo Action'), ('workflow_reverted', 'Workflow Reverted'), ('section_assigned', 'Section Assigned')], help_text='Type of action performed', max_length=100)),
                ('old_status', models.CharField(blank=True, help_text='Previous status (for status_changed action)', max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, help_text='New status (for status_changed action)', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('file_names', models.TextField(blank=True, help_text='JSON list of file names (for files_uploaded action)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='Submission this log entry belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='document_tracking.submission')),
            ],
            options={
                'verbose_name': 'Logbook Entry',
                'verbose_name_plural': 'Logbook Entries',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrackingNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for this sequence')),
                ('last_serial', models.IntegerField(default=0, help_text='Last serial number used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(help_text='Document type this sequence belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='document_tracking.documenttype')),
            ],
            options={
                'verbose_name': 'Tracking Number Sequence',
                'verbose_name_plural': 'Tracking Number Sequences',
                'ordering': ['-year', 'document_type'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='document_tr_status_ecdeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_by'], name='document_tr_submitt_e7cf58_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tracking_number'], name='document_tr_trackin_01c970_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['document_type'], name='document_tr_documen_d9481f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assigned_section'], name='document_tr_assigne_c9377d_idx'),
        ),
        migrations.AddIndex(
            model_name='logbook',
            index=models.Index(fields=['submission', 'timestamp'], name='document_tr_submiss_0977db_idx'),
        ),
        migrations.AddIndex(
            model_name='logbook',
            index=models.Index(fields=['action'], name='document_tr_action_2fa8a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingnumbersequence',
            unique_together={('document_type', 'year')},
        ),
    ]
