# Generated by Django 5.0.7 on 2026-02-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder display name', max_length=150)),
                ('folder_type', models.CharField(choices=[('root', 'Root'), ('year', 'Year'), ('category', 'Category'), ('workcycle', 'Work Cycle'), ('workforces_department', 'Workforces Department'), ('attachment', 'Attachment')], db_index=True, max_length=25)),
                ('is_system_generated', models.BooleanField(default=True, help_text='True = system hierarchy folder, False = user-created folder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='structure.documentfolder')),
                ('workcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='accounts.workcycle')),
                ('workforces_department', models.ForeignKey(blank=True, help_text='Department this folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='accounts.workforcesdepartment')),
            ],
            options={
                'ordering': ['folder_type', 'name'],
                'indexes': [models.Index(fields=['folder_type'], name='structure_d_folder__a44da2_idx'), models.Index(fields=['parent'], name='structure_d_parent__264eb7_idx'), models.Index(fields=['workcycle'], name='structure_d_workcyc_5e9408_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_folder_name_per_parent'),
        ),
    ]
