"""
Django settings for penro_project project.
Generated by 'django-admin startproject' using Django 5.2.9
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# -------------------------------------------------
# BASE
# -------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------
# SECURITY
# -------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set!")

DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')

SECURE_REDIRECT_EXEMPT = [r'^auth/login/$']

LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/auth/login/"

# -------------------------------------------------
# APPLICATIONS
# -------------------------------------------------
INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project apps
    "accounts.apps.AccountsConfig",
    "notifications.apps.NotificationsConfig",
    "admin_app",
    "user_app",
    "structure",
    "document_tracking",  # Digital Document Tracking System
]

# -------------------------------------------------
# AUTH
# -------------------------------------------------
AUTH_USER_MODEL = "accounts.User"

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameBackend',  # Allow login with email or username
    'django.contrib.auth.backends.ModelBackend',  # Keep default as fallback
]

# -------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add whitenoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # Custom middleware
    "middleware.auth_required.LoginRequiredMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Allow iframes from same origin (for discussion modal)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# -------------------------------------------------
# URLS / WSGI
# -------------------------------------------------
ROOT_URLCONF = "penro_project.urls"
WSGI_APPLICATION = "penro_project.wsgi.application"

# -------------------------------------------------
# TEMPLATES
# -------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Notification counts - re-enabled for immediate display
                'user_app.context_processors.user_unread_notifications',
                'admin_app.context_processors.admin_unread_notifications',
                # Role-based layout selection for document tracking
                'document_tracking.context_processors.layout_context',
                # PERFORMANCE NOTE: These add 1-2 queries per page load
                # but provide instant notification counts on page load
                # Disabled for performance (use AJAX instead):
                # 'user_app.context_processors.unread_discussions',
                # 'user_app.context_processors.user_unread_emails',
                # 'admin_app.context_processors.admin_unread_discussions',
                # 'admin_app.context_processors.admin_unread_emails',
            ],
        },
    }
]

# -------------------------------------------------
# DATABASE
# -------------------------------------------------
# Use PostgreSQL if DATABASE_URL is provided, otherwise SQLite3
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # PostgreSQL configuration for production
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
    print("[OK] PostgreSQL database enabled (PRODUCTION MODE)")
    print(f"  Database: {DATABASE_URL.split('@')[1].split('/')[0] if '@' in DATABASE_URL else 'PostgreSQL'}")
else:
    # SQLite3 configuration for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    print("[OK] SQLite3 database enabled (DEVELOPMENT MODE)")
    print(f"  Database file: {BASE_DIR / 'db.sqlite3'}")

# -------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------
# STATIC & MEDIA
# -------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise configuration for production static files
# Use CompressedStaticFilesStorage (without Manifest) to avoid issues with ICO files
# This still compresses files but doesn't add hashes to filenames
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Memory optimization - disable unnecessary features in production
if not DEBUG:
    # Reduce session cookie age to free memory faster
    SESSION_COOKIE_AGE = 86400  # 1 day instead of 2 weeks
    SESSION_SAVE_EVERY_REQUEST = False
    
    # Limit file upload size to prevent memory issues
    DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
    FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# -------------------------------------------------
# CACHING (PERFORMANCE OPTIMIZATION)
# -------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Cache timeout settings (in seconds)
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'penro'

# Session caching for better performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# -------------------------------------------------
# CLOUDINARY CONFIGURATION
# -------------------------------------------------
# Check if Cloudinary credentials are provided
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    # Cloudinary configuration for production
    CLOUDINARY_ENABLED = True
    
    # Add cloudinary to installed apps
    if 'cloudinary_storage' not in INSTALLED_APPS:
        INSTALLED_APPS.append('cloudinary_storage')
    if 'cloudinary' not in INSTALLED_APPS:
        INSTALLED_APPS.append('cloudinary')
    
    # Cloudinary settings
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
    
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True
    )
    
    # Use Cloudinary for media files
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = '/media/'
    
    print("[OK] Cloudinary storage enabled (PRODUCTION MODE)")
    print(f"  Cloud name: {CLOUDINARY_CLOUD_NAME}")
else:
    # Local file storage for development
    CLOUDINARY_ENABLED = False
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
    print("[OK] Local file storage enabled (DEVELOPMENT MODE)")
    print(f"  Media files will be stored in: {MEDIA_ROOT}")

# -------------------------------------------------
# DEFAULTS
# -------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------------------------------
# EMAIL CONFIGURATION
# -------------------------------------------------
# Using Brevo API (not SMTP) for better reliability on Render
# SMTP settings kept for backward compatibility but not required

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# SMTP settings (optional, not used when using Brevo API)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp-relay.brevo.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == 'true'
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# Brevo API configuration (primary method)
BREVO_API_KEY = os.getenv("BREVO_API_KEY")

# Default sender email
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", 
    "PENRO WISE Notifications <penrowisenotifications@gmail.com>"
)

# Validate that at least one email method is configured
if not BREVO_API_KEY and not EMAIL_HOST_PASSWORD:
    import warnings
    warnings.warn(
        "Neither BREVO_API_KEY nor EMAIL_HOST_PASSWORD is set. "
        "Email sending will not work. Please configure one of them."
    )

# -------------------------------------------------
# APSCHEDULER CONTROL (IMPORTANT)
# -------------------------------------------------
# Toggle scheduler ON/OFF
ENABLE_SCHEDULER = True

# -------------------------------------------------
# LOGGING (SHOW APSCHEDULER LOGS)
# -------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
