# Generated by Django 5.2.9 on 2026-01-02 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemattachment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='structure.documentfolder'),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Uploader (null only for system/admin actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.workitem'),
        ),
        migrations.AddField(
            model_name='workitemmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemmessage',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.workitem'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_team_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='orgassignment',
            constraint=models.UniqueConstraint(fields=('user',), name='one_org_assignment_per_user'),
        ),
        migrations.AddIndex(
            model_name='workcycle',
            index=models.Index(fields=['due_at'], name='accounts_wo_due_at_3a64ce_idx'),
        ),
        migrations.AddIndex(
            model_name='workcycle',
            index=models.Index(fields=['is_active'], name='accounts_wo_is_acti_86216c_idx'),
        ),
        migrations.AddConstraint(
            model_name='workassignment',
            constraint=models.CheckConstraint(check=models.Q(('assigned_user__isnull', False), ('assigned_team__isnull', False), _connector='OR'), name='workassignment_requires_user_or_team'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status'], name='accounts_wo_status_8b61a8_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['review_decision'], name='accounts_wo_review__a054a1_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['is_active'], name='accounts_wo_is_acti_98b501_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['inactive_reason'], name='accounts_wo_inactiv_c3c8a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workitem',
            unique_together={('workcycle', 'owner')},
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['attachment_type'], name='accounts_wo_attachm_1c4674_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['folder'], name='accounts_wo_folder__c2c20f_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['work_item', 'folder'], name='accounts_wo_work_it_4d63d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitemattachment',
            constraint=models.UniqueConstraint(fields=('folder', 'file'), name='unique_file_per_folder'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['sender_role'], name='accounts_wo_sender__2b1a85_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['created_at'], name='accounts_wo_created_b13a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['is_read'], name='accounts_wo_is_read_cdd92e_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['work_item', 'is_read'], name='accounts_wo_work_it_25e1b5_idx'),
        ),
    ]
