# Generated by Django 5.2.9 on 2026-01-04 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='workitemmessage',
            name='accounts_wo_is_read_cdd92e_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitemmessage',
            name='accounts_wo_work_it_25e1b5_idx',
        ),
        migrations.AlterField(
            model_name='workitemmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='LEGACY: do not use for chat read logic'),
        ),
        migrations.AlterField(
            model_name='workitemmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='LEGACY: do not use for chat read logic', null=True),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['work_item', 'created_at'], name='accounts_wo_work_it_00661b_idx'),
        ),
        migrations.AddField(
            model_name='workitemreadstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.workitemmessage'),
        ),
        migrations.AddField(
            model_name='workitemreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemreadstate',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='accounts.workitem'),
        ),
        migrations.AddIndex(
            model_name='workitemreadstate',
            index=models.Index(fields=['work_item', 'user'], name='accounts_wo_work_it_4abaec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workitemreadstate',
            unique_together={('work_item', 'user')},
        ),
    ]
