# Generated by Django 5.2.9 on 2026-01-06 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='inactive_by',
            field=models.ForeignKey(blank=True, help_text='User who archived or deactivated this work item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['inactive_by'], name='accounts_wo_inactiv_cfb688_idx'),
        ),
    ]
