# Generated by Django 5.2.9 on 2026-01-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_orgassignment_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.team'),
        ),
    ]
