# Generated by Django 5.0.7 on 2026-01-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_hidden_discussion_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='workitemattachment',
            name='file',
            field=models.FileField(help_text='Uploaded file', upload_to='work_items/'),
        ),
    ]
