# Generated by Django 5.0.7 on 2026-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_make_work_item_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemattachment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the file was reviewed by admin', null=True),
        ),
    ]
