# Generated by Django 5.2.9 on 2026-01-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_reviewed_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitemattachment',
            name='attachment_type',
            field=models.CharField(choices=[('matrix_a', 'Matrix A'), ('matrix_b', 'Matrix B'), ('mov', 'MOV'), ('document', 'Document'), ('admin_upload', 'Admin Upload')], db_index=True, default='document', help_text='Type of attachment (matrix_a, matrix_b, mov for work items; document for standalone)', max_length=20),
        ),
    ]
