# Generated by Django 5.0.7 on 2026-01-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_link_title'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workitemattachment',
            name='unique_file_per_folder',
        ),
        migrations.AddConstraint(
            model_name='workitemattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('link_url__isnull', True)), fields=('folder', 'file'), name='unique_file_per_folder'),
        ),
    ]
