# Generated by Django 5.0.7 on 2026-01-31 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_fix_unique_constraint_for_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCycleEmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('reassigned', 'Reassigned')], db_index=True, help_text='Type of email notification to send', max_length=20)),
                ('old_due_at', models.DateTimeField(blank=True, help_text='Old due date (for edited jobs)', null=True)),
                ('inactive_note', models.TextField(blank=True, help_text='Reassignment note (for reassigned jobs)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcycle_email_jobs', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_jobs', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_wo_status_822809_idx'), models.Index(fields=['job_type', 'status'], name='accounts_wo_job_typ_7fe4c0_idx')],
            },
        ),
    ]
