# Generated by Django 5.0.7 on 2026-02-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemattachment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='structure.documentfolder'),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who accepted/rejected this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Uploader (null only for system/admin actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='work_item',
            field=models.ForeignKey(blank=True, help_text='Work item this file belongs to (null for standalone file manager uploads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.workitem'),
        ),
        migrations.AddField(
            model_name='workitemmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemmessage',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.workitem'),
        ),
        migrations.AddField(
            model_name='workitemreadstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.workitemmessage'),
        ),
        migrations.AddField(
            model_name='workitemreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemreadstate',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='accounts.workitem'),
        ),
        migrations.AddField(
            model_name='workitemreviewjob',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workitem_review_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemreviewjob',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_jobs', to='accounts.workitem'),
        ),
        migrations.AddField(
            model_name='workitemstatusjob',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workitem_status_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemstatusjob',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_jobs', to='accounts.workitem'),
        ),
        migrations.AddIndex(
            model_name='workcycle',
            index=models.Index(fields=['due_at'], name='accounts_wo_due_at_3a64ce_idx'),
        ),
        migrations.AddIndex(
            model_name='workcycle',
            index=models.Index(fields=['is_active'], name='accounts_wo_is_acti_86216c_idx'),
        ),
        migrations.AddIndex(
            model_name='workcycleemailjob',
            index=models.Index(fields=['status', 'created_at'], name='accounts_wo_status_822809_idx'),
        ),
        migrations.AddIndex(
            model_name='workcycleemailjob',
            index=models.Index(fields=['job_type', 'status'], name='accounts_wo_job_typ_7fe4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='workcyclejob',
            index=models.Index(fields=['status', 'created_at'], name='accounts_wo_status_5de5d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='workassignment',
            constraint=models.CheckConstraint(check=models.Q(('assigned_user__isnull', False), ('assigned_department__isnull', False), _connector='OR'), name='workassignment_requires_user_or_department'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status'], name='accounts_wo_status_8b61a8_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['review_decision'], name='accounts_wo_review__a054a1_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['is_active'], name='accounts_wo_is_acti_98b501_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['inactive_reason'], name='accounts_wo_inactiv_c3c8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['inactive_by'], name='accounts_wo_inactiv_cfb688_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workitem',
            unique_together={('workcycle', 'owner')},
        ),
        migrations.AddIndex(
            model_name='hiddendiscussion',
            index=models.Index(fields=['hidden_by', 'hide_type'], name='accounts_hi_hidden__7179bf_idx'),
        ),
        migrations.AddIndex(
            model_name='hiddendiscussion',
            index=models.Index(fields=['hidden_by', 'work_item'], name='accounts_hi_hidden__c7a687_idx'),
        ),
        migrations.AddIndex(
            model_name='hiddendiscussion',
            index=models.Index(fields=['hidden_by', 'workcycle'], name='accounts_hi_hidden__3e346c_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiddendiscussion',
            constraint=models.UniqueConstraint(condition=models.Q(('hide_type', 'work_item')), fields=('hidden_by', 'work_item'), name='unique_hidden_work_item'),
        ),
        migrations.AddConstraint(
            model_name='hiddendiscussion',
            constraint=models.UniqueConstraint(condition=models.Q(('hide_type', 'workcycle')), fields=('hidden_by', 'workcycle'), name='unique_hidden_workcycle'),
        ),
        migrations.AddConstraint(
            model_name='hiddendiscussion',
            constraint=models.UniqueConstraint(condition=models.Q(('hide_type', 'user_thread')), fields=('hidden_by', 'hidden_user', 'workcycle'), name='unique_hidden_user_thread'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['attachment_type'], name='accounts_wo_attachm_1c4674_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['folder'], name='accounts_wo_folder__c2c20f_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['work_item', 'folder'], name='accounts_wo_work_it_4d63d9_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['acceptance_status'], name='accounts_wo_accepta_a022ce_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemattachment',
            index=models.Index(fields=['rejection_expires_at'], name='accounts_wo_rejecti_abaa88_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitemattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('link_url__isnull', True)), fields=('folder', 'file'), name='unique_file_per_folder'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['sender_role'], name='accounts_wo_sender__2b1a85_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['created_at'], name='accounts_wo_created_b13a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['work_item', 'created_at'], name='accounts_wo_work_it_00661b_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemreadstate',
            index=models.Index(fields=['work_item', 'user'], name='accounts_wo_work_it_4abaec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workitemreadstate',
            unique_together={('work_item', 'user')},
        ),
        migrations.AddIndex(
            model_name='workitemreviewjob',
            index=models.Index(fields=['status', 'created_at'], name='workitem_re_status_c60052_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemstatusjob',
            index=models.Index(fields=['status', 'created_at'], name='workitem_st_status_1348bd_idx'),
        ),
    ]
