# Generated by Django 5.0.7 on 2026-02-16 08:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforcesDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workforces Department', help_text='Department name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional department description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workforces Department',
                'verbose_name_plural': 'Workforces Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('matrix_a', 'Matrix A'), ('matrix_b', 'Matrix B'), ('mov', 'MOV'), ('document', 'Document'), ('admin_upload', 'Admin Upload')], db_index=True, default='document', help_text='Type of attachment (matrix_a, matrix_b, mov for work items; document for standalone)', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (null for link attachments)', null=True, upload_to='work_items/')),
                ('link_url', models.URLField(blank=True, help_text='URL for link attachments (alternative to file upload)', max_length=500, null=True)),
                ('link_title', models.CharField(blank=True, help_text='Title/name for link attachments (displayed in file manager)', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Admin acceptance status for this file', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the file was accepted', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When the file was rejected', null=True)),
                ('rejection_expires_at', models.DateTimeField(blank=True, help_text='When rejected file will be auto-deleted (24h after rejection)', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the file was reviewed by admin', null=True)),
                ('rejection_reason', models.CharField(blank=True, help_text='Optional reason for rejection', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_index=True, help_text='Role of the sender at the time the message was sent', max_length=50)),
                ('message', models.TextField(help_text='Message regarding status, review, or work clarification')),
                ('related_status', models.CharField(blank=True, help_text='Status this message refers to (optional)', max_length=30)),
                ('related_review', models.CharField(blank=True, help_text='Review decision this message refers to (optional)', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='LEGACY: do not use for chat read logic')),
                ('read_at', models.DateTimeField(blank=True, help_text='LEGACY: do not use for chat read logic', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItemReviewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_decision', models.CharField(max_length=30)),
                ('new_decision', models.CharField(max_length=30)),
                ('file_stats', models.JSONField(blank=True, default=dict, help_text='File statistics (accepted/rejected counts, file names)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workitem_review_jobs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemStatusJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workitem_status_jobs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position_title', models.CharField(blank=True, help_text='Job title or designation', max_length=150)),
                ('profile_image', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_images/')),
                ('login_role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_index=True, default='user', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, help_text="User's department assignment", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.workforcesdepartment')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_items', models.PositiveIntegerField(default=0, help_text='Total work items assigned to user')),
                ('completed_work_items', models.PositiveIntegerField(default=0, help_text='Work items marked as done')),
                ('on_time_submissions', models.PositiveIntegerField(default=0, help_text='Submissions made before deadline')),
                ('late_submissions', models.PositiveIntegerField(default=0, help_text='Submissions made after deadline')),
                ('approved_work_items', models.PositiveIntegerField(default=0, help_text='Work items approved by admin')),
                ('revision_requests', models.PositiveIntegerField(default=0, help_text='Work items sent back for revision')),
                ('total_files_uploaded', models.PositiveIntegerField(default=0, help_text='Total files uploaded by user')),
                ('accepted_files', models.PositiveIntegerField(default=0, help_text='Files accepted by admin')),
                ('rejected_files', models.PositiveIntegerField(default=0, help_text='Files rejected by admin')),
                ('on_time_ratio', models.FloatField(default=0.0, help_text='Percentage of on-time submissions (0-100)')),
                ('approval_ratio', models.FloatField(default=0.0, help_text='Percentage of approved work items (0-100)')),
                ('file_acceptance_ratio', models.FloatField(default=0.0, help_text='Percentage of accepted files (0-100)')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, help_text='When metrics were last recalculated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
            },
        ),
        migrations.CreateModel(
            name='WorkCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task, report, or work cycle', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional details or instructions')),
                ('due_at', models.DateTimeField(help_text='Deadline for this work cycle')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive work cycles are hidden / archived manually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this work cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workcycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCycleEmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('reassigned', 'Reassigned')], db_index=True, help_text='Type of email notification to send', max_length=20)),
                ('old_due_at', models.DateTimeField(blank=True, help_text='Old due date (for edited jobs)', null=True)),
                ('inactive_note', models.TextField(blank=True, help_text='Reassignment note (for reassigned jobs)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcycle_email_jobs', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_jobs', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCycleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this job has been retried')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Assign directly to a specific user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(help_text='Work cycle being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.workcycle')),
                ('assigned_department', models.ForeignKey(blank=True, help_text='Assign to entire department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='accounts.workforcesdepartment')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive items are archived or closed for a specific reason')),
                ('inactive_reason', models.CharField(blank=True, choices=[('reassigned', 'Reassigned'), ('duplicate', 'Duplicate Submission'), ('invalid', 'Invalid / Not Required'), ('superseded', 'Superseded by New Submission'), ('archived', 'Archived After Completion')], db_index=True, help_text='Reason why this work item became inactive', max_length=50)),
                ('inactive_note', models.CharField(blank=True, help_text='Optional explanation or comment', max_length=255)),
                ('inactive_at', models.DateTimeField(blank=True, help_text='Timestamp when this item became inactive', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('working_on_it', 'Working on It'), ('done', 'Done (Submitted)')], db_index=True, default='not_started', max_length=30)),
                ('status_label', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('review_decision', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revision', 'Needs Revision')], db_index=True, default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inactive_by', models.ForeignKey(blank=True, help_text='User who archived or deactivated this work item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_work_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiddenDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_type', models.CharField(choices=[('work_item', 'Work Item'), ('workcycle', 'Work Cycle'), ('user_thread', 'User Thread')], default='work_item', max_length=20)),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('hidden_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_discussions', to=settings.AUTH_USER_MODEL)),
                ('hidden_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads_hidden_by_admins', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_admins', to='accounts.workcycle')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='accounts.workitem')),
            ],
        ),
    ]
