# Generated by Django 5.0.7 on 2026-02-16 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='Email address used as sender', max_length=254)),
                ('recipient_email', models.EmailField(help_text='Email address of recipient', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(help_text='Plain text version of email body')),
                ('body_html', models.TextField(blank=True, help_text='HTML version of email body (optional)')),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('org_change', 'Organization Change'), ('profile_update', 'Profile Update'), ('password_reset', 'Password Reset'), ('notification', 'Notification'), ('system', 'System Email'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if email failed to send')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the recipient has read this email')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the email was marked as read', null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='User who received the email (null for external recipients)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered the email (null for system emails)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_abb114_idx'), models.Index(fields=['sender', 'created_at'], name='notificatio_sender__a509d2_idx'), models.Index(fields=['email_type'], name='notificatio_email_t_4e53a9_idx'), models.Index(fields=['status'], name='notificatio_status_18a272_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_f3db12_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('status', 'Status'), ('review', 'Review'), ('assignment', 'Assignment'), ('message', 'Message'), ('system', 'System')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], db_index=True, default='info', max_length=20)),
                ('title', models.CharField(help_text='Short headline shown in notification list', max_length=200)),
                ('message', models.TextField(help_text='Detailed message shown when expanded')),
                ('action_url', models.CharField(blank=True, help_text='Optional URL the notification should link to', max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.workitem')),
                ('workcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['category'], name='notificatio_categor_fd561f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['recipient', 'category', 'is_read'], name='notificatio_recipie_130037_idx')],
            },
        ),
    ]
